backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "media" #specifies where uploaded files are saved in the repo
public_folder: "/media" #indicates where they are found in the published site

collections:
  - name: "diary"
    label: "Diary"
    folder: "entries/diary"
    create: true
    slug: "{{month}}-{{day}}-{{year}}"
    fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Date", name: "date", widget: "datetime", date-format: "MM-DD-YYYY", time-format:"hh:mm A"}
    - { label: "Body", name: "body", widget: "markdown" }
    



